services:
  api:
    build: .
    ports:
      - '8082:8082'
    container_name: pet-api
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://192.168.31.146:5432/pet
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=12345678
      - TELEGRAM_TOKEN=${TELEGRAM_TOKEN}
      - YA_KEY=${YA_KEY}
      - YA_ID=${YA_ID}
      - SBER_SECRET=${SBER_SECRET}