services:
  api:
    build: .
    ports:
      - '8082:8082'
      - '5432:5432'
    container_name: pet-api
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://localhost:5432/pet
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=12345678